### ISSUE TITLE
EINVAL: invalid argument, mkdir 'docs\:'

### ISSUE THREAD

**Issue by FabienHuot** [cesarParra/apexdocs#19]
Hi,

I wanted to make it work, but there is something I really don't understand.
When I'm executing the command, it throw this error.

In the end, in my project, I see that a new folder has been created "docs" (default), and a readme.md. But there is nothing inside the readme.md.

I'm not able to make it work, do you have any idea ? Below, the code where you can see the error.

Thanks a lot !

```
$ apexdocs-generate -s force-app/main/default/classes/
Processed 1 files
internal/fs/utils.js:314
    throw err;
    ^

Error: EINVAL: invalid argument, mkdir 'docs\:'
    at Object.mkdirSync (fs.js:1009:3)
    at JekyllDocsProcessor.process (C:\Users\fabie\AppData\Roaming\npm\node_modules\@cparra\apexdocs\lib\MarkdownDocsProcessor.js:80:20)
    at C:\Users\fabie\AppData\Roaming\npm\node_modules\@cparra\apexdocs\lib\FileManager.js:24:27
    at Array.forEach (<anonymous>)
    at FileManager.generate (C:\Users\fabie\AppData\Roaming\npm\node_modules\@cparra\apexdocs\lib\FileManager.js:23:23)
    at Object.<anonymous> (C:\Users\fabie\AppData\Roaming\npm\node_modules\@cparra\apexdocs\lib\cli\generate.js:53:49)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  errno: -4071,
  syscall: 'mkdir',
  code: 'EINVAL',
  path: 'docs\\:'
}
```

**Comment by cesarParra** [comment]
I see. Haven't come across this issue before, so this is a total shot in the dark, but looking at the error message it looks like it could be an issue with your node installation ([example](https://stackoverflow.com/questions/66921919/error-einval-invalid-argument-mkdir-c-users-user-c-users-user-appdata-roa))

If you run `npm -v`, are you getting the error as well?

**Comment by FabienHuot** [comment]
Hi Cesar,
Yes, I saw this kind of post when I have investigated. As you said, it seems that the problem came from my npm installation.
This is quite funny because I installed npm yesterday =D

If I run `npm -v` no issue. I got my version (6.14.13).

I'll continue to investigate to be able to make your plugin work ! I really want to use your plugin =)

Thanks for your time.
I close the issue

**Comment by jeremyvial** [comment]
I have the same error 

`> apexdocs-generate -s ./force-app/main/default -t docs -r

Processed 1 files
internal/fs/utils.js:307
    throw err;
    ^

Error: EINVAL: invalid argument, mkdir 'docs\:'
    at Object.mkdirSync (fs.js:987:3)
    at JekyllDocsProcessor.process (C:\Users\jrmdu\Desktop\Nouveau dossier (2)\node_modules\@cparra\apexdocs\lib\MarkdownDocsProcessor.js:80:20)
    at C:\Users\jrmdu\Desktop\Nouveau dossier (2)\node_modules\@cparra\apexdocs\lib\FileManager.js:24:27
    at Array.forEach (<anonymous>)
    at FileManager.generate (C:\Users\jrmdu\Desktop\Nouveau dossier (2)\node_modules\@cparra\apexdocs\lib\FileManager.js:23:23)
    at Object.<anonymous> (C:\Users\jrmdu\Desktop\Nouveau dossier (2)\node_modules\@cparra\apexdocs\lib\cli\generate.js:53:49)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  errno: -4071,
  syscall: 'mkdir',
  code: 'EINVAL',
  path: 'docs\\:'
}`

When i correct directly the path in **node_modules\@cparra\apexdocs\lib\MarkdownDocsProcessor.js** the error disapeared

**Comment by cesarParra** [comment]
Closing. Feel free to reopen if the issue pops up again.

**Comment by ZaraBaghdasaryan** [comment]
Hi, I am having the exact same problem and I didn't really understand how you resolved it. Could you please help me with all the steps you took to fix it? I have been trying every solution I can find with no luck so far :( 

Thank you so much in advance for all your help!
![3](https://user-images.githubusercontent.com/74423786/220089601-a7071dc4-ab11-4eb4-acd2-a6a3284ebf08.PNG)

**Comment by dllewellyn-VillageMd** [comment]
I think you need to change your @group tag to not include a *. Somehow, somewhere you've got an asterisk getting fed into the path name which is not a valid name for a folder.

**Comment by ZaraBaghdasaryan** [comment]
Hi @Kenji776, thank you so much for reaching out! 😊 I have also heard that it could be a non existing directory that the path is referring to, where could I find the @group tag to change it so that the path will be corrected?
