### ISSUE TITLE
MODULE_NOT_FOUND when installed globally

### ISSUE THREAD

**Issue by cceremuga** [cesarParra/apexdocs#2]
When installing with `-g` to make it available system-wide, the command fails with MODULE_NOT_FOUND.

```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '../command/Generate'
Require stack:
- /usr/local/lib/node_modules/@cparra/apexdocs/lib/cli/generate.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cparra/apexdocs/lib/cli/generate.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@cparra/apexdocs/lib/cli/generate.js'
  ]
}
```

OS: Linux
Node Version: 12.16.1
NPM Version: 6.14.2

I suspect it _may_ be due to case sensitivity on this OS. The actual `Command` folder has a capital `C` with the stracktrace showing it's trying to load a lowercase `c`.

**Comment by cesarParra** [comment]
Thanks @cceremuga , that is a good call. I regenerated the entire `lib` folder since the casing for some of the folders in there were different when compared to `src`, so my best guess is that at some point the folder names were refactored but kept the old names in `lib`.

Can you give it another try on the latest published version (1.9.4)?

**Comment by cceremuga** [comment]
@cesarParra hmmm same error. Should anything have changed besides the version number?

**Comment by cesarParra** [comment]
@cceremuga The `lib` directory is being ignored on Github, but the npm package includes it, so the directory names being downloaded to the `node_modules` directory should be different.

**Comment by cceremuga** [comment]
Good to go, that fixed it once I did a full uninstall / reinstall. Thanks! 💯
