### ISSUE TITLE
Error while running apex docs

### ISSUE THREAD

**Issue by RaviVaranasi** [cesarParra/apexdocs#201]
I got the latest version, 3.4.0, and ran the following command.

`apexdocs markdown -s force-app`

```
/Users/ravi.varanasi/salesforce-project/node_modules/@cparra/apexdocs/dist/logger-BJXlA0YD.js:1743
  return text.toLowerCase().replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-").replace(/-+/g, "-");
              ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at slugify (/Users/ravi.varanasi/salesforce-project/node_modules/@cparra/apexdocs/dist/logger-BJXlA0YD.js:1743:15)
    at parsedFileToDocPageReference (/Users/ravi.varanasi/salesforce-project/node_modules/@cparra/apexdocs/dist/logger-BJXlA0YD.js:1734:19)
    at /Users/ravi.varanasi/salesforce-project/node_modules/@cparra/apexdocs/dist/logger-BJXlA0YD.js:1729:35
    at Array.reduce (<anonymous>)
    at parsedFilesToReferenceGuide (/Users/ravi.varanasi/salesforce-project/node_modules/@cparra/apexdocs/dist/logger-BJXlA0YD.js:1728:22)
    at /Users/ravi.varanasi/salesforce-project/node_modules/@cparra/apexdocs/dist/logger-BJXlA0YD.js:51:27
    at /Users/ravi.varanasi/salesforce-project/node_modules/@cparra/apexdocs/dist/logger-BJXlA0YD.js:2144:9
    at /Users/ravi.varanasi/salesforce-project/node_modules/fp-ts/lib/Chain.js:15:103
    at /Users/ravi.varanasi/salesforce-project/node_modules/fp-ts/lib/EitherT.js:99:97
    at /Users/ravi.varanasi/salesforce-project/node_modules/fp-ts/lib/Task.js:134:41

Node.js v18.19.0
```

**Comment by cesarParra** [comment]
Thanks @RaviVaranasi .

Seems like I have a typo in the new config param. I'll fix this shortly. As a workaround you can try adding the "customObjectsGroupName" (notice the extra "s" after Object) key to your config file

**Comment by RaviVaranasi** [comment]
> bjects

Is this in the metadata xml file or is it a apex docs config file?

**Comment by RaviVaranasi** [comment]
Never mind. Figured it out

**Comment by cesarParra** [comment]
New version (3.4.1) available
